version: "3.9"
services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./teszt:/srv/http
      - ./nginx:/etc/nginx/conf.d
    workdir: /srv/http
    ports:
      - "80:80"
    links:
      - php

  php:
    build: ./php8-fpm-image
    volumes:
      - ./teszt:/srv/http
    links:
      - db

  db:
    image: postgres:alpine
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: payment
      POSTGRES_USER: paymentgateway
